#pragma once

#include <map>
#include <string>
#include <vector>

#include "../include/pg_generic.hpp"

/** @file */
namespace pg {
namespace ws {
static const std::vector<std::pair<std::string, uint8_t>> commands{
    {"o", 1},
    {"tex", 2},
    {"cam", 3},
    {"ws", 4},
    {"tb", 5},
    {"db", 6},
    {"ad", 7},
    {"txt", 8},
};

enum names {
    START_N1,
    POSX,
    POSY,
    POSZ,
    WIDTH,
    HEIGHT,
    ROTX,
    ROTY,
    ROTZ,
    CUTX,
    CUTY,
    CUTW,
    CUTH,
    ORIX,
    ORIY,
    ORIZ,
    R,
    G,
    B,
    A,
    TEXID,
    E,
    TBID,
    TBOFF,
    WSID,
    SAMID,
    IBID,
    IBOFF,
    MANAGE,
    TARX,
    TARY,
    TARZ,
    FOVY,
    AR,
    DDD,
    ADDWSID,
    RMWSID,
    ID,
    PATH,
    BSIZE,
    OBJID
};

static const std::map<std::string, uint8_t> attributeNames{
    {"POSX", POSX},
    {"POSY", POSY},
    {"POSZ", POSZ},
    {"WIDTH", WIDTH},
    {"HEIGHT", HEIGHT},
    {"ROTX", ROTX},
    {"ROTY", ROTY},
    {"ROTZ", ROTZ},
    {"CUTX", CUTX},
    {"CUTY", CUTY},
    {"CUTW", CUTW},
    {"CUTH", CUTH},
    {"ORIX", ORIX},
    {"ORIY", ORIY},
    {"ORIZ", ORIZ},
    {"R", R},
    {"G", G},
    {"B", B},
    {"A", A},
    {"TEXID", TEXID},
    {"E", E},
    {"TBID", TBID},
    {"TBOFF", TBOFF},
    {"WSID", WSID},
    {"SAMID", SAMID},
    {"IBID", IBID},
    {"IBOFF", IBOFF},
    {"MANAGE", MANAGE},
    {"TARX", TARX},
    {"TARY", TARY},
    {"TARZ", TARZ},
    {"FOVY", FOVY},
    {"AR", AR},
    {"DDD", DDD},
    {"ADDWSID", ADDWSID},
    {"RMWSID", RMWSID},
    {"ID", ID},
    {"PATH", PATH},
    {"BSIZE", BSIZE},
    {"OBJID", OBJID},
    {"SIZE", WIDTH},
    {"CUTPOS", CUTX},
    {"CUTSIZE", CUTW},
    {"POS", POSX},
    {"ROT", ROTX},
    {"TAR", TARX},
    {"ORIPOS", ORIX},
    {"COLOR", R}};

static const std::map<uint8_t, int> attributesPG{
    {POSX, pg::POSITION_X},
    {POSY, pg::POSITION_Y},
    {POSZ, pg::POSITION_Z},
    {WIDTH, pg::WIDTH},
    {HEIGHT, pg::HEIGHT},
    {ROTX, pg::ROTATION_X},
    {ROTY, pg::ROTATION_Y},
    {ROTZ, pg::ROTATION_Z},
    {CUTX, pg::CUT_X},
    {CUTY, pg::CUT_Y},
    {CUTW, pg::CUT_WIDTH},
    {CUTH, pg::CUT_HEIGHT},
    {ORIX, pg::ORIGIN_X},
    {ORIY, pg::ORIGIN_Y},
    {ORIZ, pg::ORIGIN_Z},
    {R, pg::RED},
    {G, pg::GREEN},
    {B, pg::BLUE},
    {A, pg::ALPHA},
    {TEXID, pg::TEXTURE_ID},
    {E, pg::ENABLED},
    {TBID, pg::TRANSFERBUFFER_ID},
    {TBOFF, pg::TRANSFERBUFFER_OFFSET},
    {WSID, pg::WORKSPACE_ID},
    {SAMID, pg::SAMPLER_ID},
    {IBID, pg::INSTANCEBUFFER_ID},
    {IBOFF, pg::INSTANCEBUFFER_OFFSET},
    {MANAGE, pg::MANAGEMENT_TYPE},
    {TARX, pg::TARGET_X},
    {TARY, pg::TARGET_Y},
    {TARZ, pg::TARGET_Z},
    {FOVY, pg::FOV_Y},
    {AR, pg::ASPECT_RATIO},
    {DDD, pg::DDD},
    {ADDWSID, pg::ADD_WORKSPACE_ID},
    {RMWSID, pg::REMOVE_WORKSPACE_ID},
};

} // namespace ws
} // namespace pg
